cn:
  "1,1p":
    b_thred: 0.1
    s_thred: 0.1
    max_sw: 0.1
    max_sl: 0.1
    dynamic_sl: 0.1
    market_value: 0.1
    score_src: area
  "2,2s":
    b_thred: 0.1
    s_thred: 0.1
    max_sw: 0.1
    max_sl: 0.1
    dynamic_sl: 0.1
    market_value: 0.1
    score_src: area
  "3":
    b_thred: 0.1
    s_thred: 0.1
    max_sw: 0.1
    max_sl: 0.1
    dynamic_sl: 0.1
    market_value: 0.1
    score_src: area
hk:
  "1,1p":
    b_thred: 0.1
    s_thred: 0.1
    max_sw: 0.1
    max_sl: 0.1
    dynamic_sl: 0.1
    market_value: 0.1
    score_src: area
  "2,2s":
    b_thred: 0.1
    s_thred: 0.1
    max_sw: 0.1
    max_sl: 0.1
    dynamic_sl: 0.1
    market_value: 0.1
    score_src: area
  "3":
    b_thred: 0.1
    s_thred: 0.1
    max_sw: 0.1
    max_sl: 0.1
    dynamic_sl: 0.1
    market_value: 0.1
    score_src: area
us:
  "1,1p":
    b_thred: 0.1
    s_thred: 0.1
    max_sw: 0.1
    max_sl: 0.1
    dynamic_sl: 0.1
    market_value: 0.1
    score_src: area
  "2,2s":
    b_thred: 0.1
    s_thred: 0.1
    max_sw: 0.1
    max_sl: 0.1
    dynamic_sl: 0.1
    market_value: 0.1
    score_src: area
  "3":
    b_thred: 0.1
    s_thred: 0.1
    max_sw: 0.1
    max_sl: 0.1
    dynamic_sl: 0.1
    market_value: 0.1
    score_src: area

