Data:
  offline_data_path: xxx
  model_path: xxx
  log_path: xxx
  stock_info_path: xxx
  pickle_data_path: xxx
  send_offline_data_update_info: True

DB:
  TYPE: sqlite  # mysql / sqlite
  HOST: 127.0.0.1
  PORT: 3306
  USER: xxx
  PASSWD: xxx
  DATABASE: xxx

  SQLITE_PATH: xxx/xxx/xxx.db

  TABLE: xxx

Futu:
  PASSWORD_MD5: xxx
  HOST: 127.0.0.1
  PORT: 11111
  RSA_PATH: ""
  ENV: SIMULATE

Trade:
  log_file: xxx
  trade_model_path: xxx
  area: cn,hk,us
  open_price_tolerance: 0.01  # relative
  open_score_tolerance: 0.03  # absolute
  chan_begin_date: 2015-01-01
  latest_ipo_date: 2021-01-01
  touch_sl_cnt: 1
  touch_sw_cnt: 1

Notion:
  cn_id: xxx
  hk_id: xxx
  us_id: xxx
  token: xxx

Model:
  model_tag: label-scale  # 开仓/后验如果没配置才取这个值
  model_type: bs_type  # normal/area/bs_type, 开仓/后验时不起作用

Chan:
  debug: false

COS:
  cos_type: xxx  # tencent/minio
  tencent_cos:
    secretid: xxx
    secretkey: xxx
    region: ap-xxx
    bucket: chan-xxx
  minio:
    endpoint: xxxx.com
    access_key: xxx
    secret_key: xxx
    bucket: xxx